### ISSUE TITLE
Support for reference times

### ISSUE THREAD

**Issue by danp** [simonw/datasette-dateutil#5]
Thanks for this plugin!

As the example says:

> dateutil_parse_fuzzy("This is due 10 september") returns 2020-09-10T00:00:00 (but will start returning the 2021 version of that if the year is 2021).

Maybe dateutil doesn't actually support this but it would be really nice to be able to give a reference time to dateutil_parse_fuzzy and probably other functions. For example, suppose I had a table like:

```
create table times (t datetime);
insert into times values (datetime('now')), (datetime('now', '-1 year')), (datetime('now', '-3 years'));
```

It would be nice to be able to do something like:

```
select t, dateutil_parse_fuzzy("This is due 10 september", t) from times
```

And have dateutil_parse_fuzzy work with t as its reference point.

**Comment by simonw** [comment]
The `parse()` function it uses does have a `default=datetime` option, which I've not tried myself: https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.parse

> -   **default** -- The default datetime object, if this is a datetime object and not `None`, elements specified in `timestr` replace elements in the default object.

**Comment by simonw** [comment]
OK, here's an example query (based on yours) I can use for this:

```sql
with times as (
  select
    datetime('now') as t
  union
  select
    datetime('now', '-1 year')
  union
  select
    datetime('now', '-3 years')
)
select t, dateutil_parse_fuzzy("This is due 10 september", t) from times
```

**Comment by simonw** [comment]
Here's a demo of this working - thanks for the suggestion! https://latest-with-plugins.datasette.io/fixtures?sql=with+times+as+%28%0D%0A++select%0D%0A++++datetime%28%27now%27%29+as+t%0D%0A++union%0D%0A++select%0D%0A++++datetime%28%27now%27%2C+%27-1+year%27%29%0D%0A++union%0D%0A++select%0D%0A++++datetime%28%27now%27%2C+%27-3+years%27%29%0D%0A%29%0D%0Aselect+t%2C+dateutil_parse_fuzzy%28%22This+is+due+10+september%22%2C+t%29+from+times

<img width="779" alt="image" src="https://user-images.githubusercontent.com/9599/156082259-f36085ff-19a1-4ff9-9334-2850ade3d830.png">

**Comment by danp** [comment]
Amazing, thank you! That will be very handy for some scraping of hand-managed sites I'm doing with https://github.com/danp/scraperlite.
